<a href="https://colab.research.google.com/github/Baeyeonho/dusghWkd/blob/main/%ED%8C%8C%EC%9D%B4%EC%8D%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
array = np.array([1, 2, 3])
print(array.size)
print(array.dtype)

3
int64
3


In [ ]:
import numpy as np

array1 = np.arange(4)
print(array1)

array2 = np.zeros((4, 4), dtype=float)
print(array2)

array3 = np.ones((3, 3), dtype=str)
print(array3)

array4 = np.random.randint(0, 10, (3, 3))
print(array4)

array5 = np.random.normal(0, 1, (3, 3))
print(array5)

[0 1 2 3]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[['1' '1' '1']
 ['1' '1' '1']
 ['1' '1' '1']]
[[3 4 5]
 [9 1 7]
 [8 4 2]]
[[ 0.61141919  1.61706913  0.60078824]
 [-0.78747579  1.27965594  0.3065278 ]
 [ 1.16959286  2.23342212 -0.61979551]]


In [ ]:
import numpy as np

array1 = np.array([1, 2, 3]) 
array2 = np.array([4, 5, 6])
array3 = np.concatenate([array1, array2])

print(array3.shape)
print(array3)

(6,)
[1 2 3 4 5 6]


In [ ]:
import numpy as np

array1 = np.arange(4).reshape(1, 4)
array2 = np.arange(8).reshape(2, 4)
array3 = np.concatenate([array1, array2], axis=0)

print(array3.shape)
print(array3)

(3, 4)
[[0 1 2 3]
 [0 1 2 3]
 [4 5 6 7]]


In [ ]:
import numpy as np

array = np.arange(8).reshape(2, 4)
left, right = np.split(array, [2], axis=1)

print(left.shape)
print(right.shape)
print(right[1][1])

(2, 2)
(2, 2)
7


In [ ]:
import numpy as np

array = np.random.randint(1, 10, size=4).reshape(2, 2)
result_array = array * 10
print(result_array)

[[30 70]
 [60 30]]


In [ ]:
import numpy as np

array1 = np.arange(4).reshape(2, 2)
array2 = np.arange(2)
array3 = array1 + array2

print(array3)

[[0 2]
 [2 4]]


In [ ]:
import numpy as np

array1 = np.arange(0, 8).reshape(2, 4)
array2 = np.arange(0, 8).reshape(2, 4)
array3 = np.concatenate([array1, array2], axis=0)
array4 = np.arange(0, 4).reshape(4, 1)

print(array3 + array4)

[[ 0  1  2  3]
 [ 5  6  7  8]
 [ 2  3  4  5]
 [ 7  8  9 10]]


In [ ]:
import numpy as np

array1 = np.arange(16).reshape(4, 4)
print(array1)

array2 = array1 < 10
print(array2)

array1[array2] = 100
print(array1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True False False]
 [False False False False]]
[[100 100 100 100]
 [100 100 100 100]
 [100 100  10  11]
 [ 12  13  14  15]]


In [ ]:
import numpy as np

array = np.arange(16).reshape(4, 4)

print("최대값:", np.max(array))
print("최소값:", np.min(array))
print("합계:", np.sum(array))
print("평균값:", np.mean(array))

최대값: 15
최소값: 0
합계: 120
평균값: 7.5


In [ ]:
import numpy as np

array = np.arange(16).reshape(4, 4)

print(array)
print("합계:", np.sum(array, axis=0))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
합계: [24 28 32 36]


In [ ]:
import numpy as np

array = np.arange(0, 10)
np.save('saved.npy', array)

result = np.load('saved.npy')
print(result)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
import numpy as np

array1 = np.arange(0, 10)
array2 = np.arange(10, 20)
np.savez('saved.npz', array1=array1, array2=array2)

data = np.load('saved.npz')
result1 = data['array1']
result2 = data['array2']
print(result1)
print(result2)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]


In [ ]:
import numpy as np

array = np.array([5, 9, 10, 3, 1])
array.sort()
print(array)

array = np.array([5, 9, 10, 3, 1])
array.sort()
print(array[::-1])

array = np.array([[5, 9, 10, 3, 1], [8, 3, 4, 2, 5]])
array.sort(axis=0)
print(array)

[ 1  3  5  9 10]
[10  9  5  3  1]
[[ 5  3  4  2  1]
 [ 8  9 10  3  5]]


In [ ]:
import numpy as np

array = np.linspace(0, 10, 5)
print(array)

np.random.seed(7)
print(np.random.randint(0, 10, (2, 3)))

array1 = np.arange(0, 10)
array2 = array1.copy()
print(array2)

array = np.array([1, 1, 2, 3, 3, 3, 1])
print(np.unique(array))